# These are supported funding model platforms

github: 
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
buy_me_a_coffee: claitonllemes
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
